import type { PetTheme, PetSpecies } from '@/types';

export const PET_THEMES: Record<PetSpecies, PetTheme> = {
  cat: {
    species: 'cat',
    name: 'Kebo',
    emoji: '🐨',
    primaryColor: '#7c3aed',
    secondaryColor: '#a78bfa',
    accentColor: '#c084fc',
    bgGradientFrom: '#f3e8ff',
    bgGradientTo: '#f7f8ff',
    cardBg: 'rgba(124, 58, 237, 0.04)',
    textPrimary: '#FFFFFF',
    textSecondary: '#FFFFFF',
    glowColor: 'rgba(124, 58, 237, 0.15)',
    particleColor: '#a78bfa',
    fontFamily: '"Inter", sans-serif',
    particleType: 'koalas',
    description: 'A tiny white koala companion with purple accents and cheerful energy.',
    personalities: ['curious', 'intelligent', 'loyal', 'mischievous'],
  },
  dog: {
    species: 'dog',
    name: 'Boba',
    emoji: '🦦',
    primaryColor: '#b45309',
    secondaryColor: '#fbbf24',
    accentColor: '#f59e0b',
    bgGradientFrom: '#fef3c7',
    bgGradientTo: '#f7f8ff',
    cardBg: 'rgba(180, 83, 9, 0.04)',
    textPrimary: '#FFFFFF',
    textSecondary: '#FFFFFF',
    glowColor: 'rgba(180, 83, 9, 0.15)',
    particleColor: '#fbbf24',
    fontFamily: '"Inter", sans-serif',
    particleType: 'boba',
    description: 'A tiny otter sipping bubble tea while keeping you company.',
    personalities: ['energetic', 'loyal', 'curious', 'mischievous'],
  },
  panda: {
    species: 'panda',
    name: 'Pixel Panda',
    emoji: '🐼',
    primaryColor: '#4b5563',
    secondaryColor: '#9ca3af',
    accentColor: '#6b7280',
    bgGradientFrom: '#f3f4f6',
    bgGradientTo: '#f7f8ff',
    cardBg: 'rgba(75, 85, 99, 0.04)',
    textPrimary: '#FFFFFF',
    textSecondary: '#FFFFFF',
    glowColor: 'rgba(75, 85, 99, 0.15)',
    particleColor: '#9ca3af',
    fontFamily: '"Inter", sans-serif',
    particleType: 'pandas',
    description: 'A gentle pixel panda holding a tiny brush.',
    personalities: ['lazy', 'intelligent', 'introverted', 'curious'],
  },
  fox: {
    species: 'fox',
    name: 'Noir Webling',
    emoji: '🕷️',
    primaryColor: '#1f2937',
    secondaryColor: '#4b5563',
    accentColor: '#111827',
    bgGradientFrom: '#e5e7eb',
    bgGradientTo: '#f7f8ff',
    cardBg: 'rgba(31, 41, 55, 0.04)',
    textPrimary: '#FFFFFF',
    textSecondary: '#FFFFFF',
    glowColor: 'rgba(31, 41, 55, 0.15)',
    particleColor: '#4b5563',
    fontFamily: '"Inter", sans-serif',
    particleType: 'webs',
    description: 'A tiny monochrome spider detective built for investigations.',
    personalities: ['mischievous', 'curious', 'energetic', 'intelligent'],
  },
  dragon: {
    species: 'dragon',
    name: 'Crafternauta',
    emoji: '🧑‍🚀',
    primaryColor: '#d97706',
    secondaryColor: '#f59e0b',
    accentColor: '#eab308',
    bgGradientFrom: '#fef9c3',
    bgGradientTo: '#f7f8ff',
    cardBg: 'rgba(217, 119, 6, 0.04)',
    textPrimary: '#FFFFFF',
    textSecondary: '#FFFFFF',
    glowColor: 'rgba(217, 119, 6, 0.15)',
    particleColor: '#f59e0b',
    fontFamily: '"Inter", sans-serif',
    particleType: 'stars',
    description: 'A tiny yellow astronaut companion with a black visor face.',
    personalities: ['intelligent', 'loyal', 'energetic', 'introverted'],
  },
  bunny: {
    species: 'bunny',
    name: 'Scoop',
    emoji: '🍦',
    primaryColor: '#ec4899',
    secondaryColor: '#fbcfe8',
    accentColor: '#f472b6',
    bgGradientFrom: '#fce7f3',
    bgGradientTo: '#f7f8ff',
    cardBg: 'rgba(236, 72, 153, 0.04)',
    textPrimary: '#FFFFFF',
    textSecondary: '#FFFFFF',
    glowColor: 'rgba(236, 72, 153, 0.15)',
    particleColor: '#ec4899',
    fontFamily: '"Inter", sans-serif',
    particleType: 'sweets',
    description: 'A tiny ice cream cone digital pet with a cheerful face.',
    personalities: ['curious', 'energetic', 'loyal', 'mischievous'],
  },
};

export function getTheme(species: PetSpecies): PetTheme {
  return PET_THEMES[species];
}

export const DEFAULT_THEME = PET_THEMES.cat;

// CSS variable names mapped to theme properties
export function applyThemeToCSSVars(theme: PetTheme): Record<string, string> {
  return {
    '--color-primary': theme.primaryColor,
    '--color-secondary': theme.secondaryColor,
    '--color-accent': theme.accentColor,
    '--bg-gradient-from': theme.bgGradientFrom,
    '--bg-gradient-to': theme.bgGradientTo,
    '--card-bg': theme.cardBg,
    '--text-primary': theme.textPrimary,
    '--text-secondary': theme.textSecondary,
    '--glow-color': theme.glowColor,
    '--particle-color': theme.particleColor,
    '--font-family': theme.fontFamily,
  };
}
