import type { PetTheme, PetSpecies } from '@/types';

export const PET_THEMES: Record<PetSpecies, PetTheme> = {
  cat: {
    species: 'cat',
    name: 'Mystic Cat',
    emoji: '🐱',
    primaryColor: '#c084fc',
    secondaryColor: '#f0abfc',
    accentColor: '#e879f9',
    bgGradientFrom: '#1a0533',
    bgGradientTo: '#2d0a4e',
    cardBg: 'rgba(192, 132, 252, 0.08)',
    textPrimary: '#f3e8ff',
    textSecondary: '#d8b4fe',
    glowColor: 'rgba(192, 132, 252, 0.4)',
    particleColor: '#e879f9',
    fontFamily: '"Outfit", sans-serif',
    particleType: 'paws',
    description: 'Mysterious and graceful, your cat graces the neon cosmos.',
    personalities: ['introverted', 'curious', 'intelligent', 'mischievous'],
  },
  dog: {
    species: 'dog',
    name: 'Golden Pup',
    emoji: '🐶',
    primaryColor: '#fb923c',
    secondaryColor: '#fbbf24',
    accentColor: '#f59e0b',
    bgGradientFrom: '#1c0a00',
    bgGradientTo: '#2d1a00',
    cardBg: 'rgba(251, 146, 60, 0.08)',
    textPrimary: '#fff7ed',
    textSecondary: '#fed7aa',
    glowColor: 'rgba(251, 146, 60, 0.4)',
    particleColor: '#fbbf24',
    fontFamily: '"Space Grotesk", sans-serif',
    particleType: 'bones',
    description: 'Energetic and loyal, your dog fills the world with warmth.',
    personalities: ['energetic', 'loyal', 'curious', 'mischievous'],
  },
  panda: {
    species: 'panda',
    name: 'Zen Panda',
    emoji: '🐼',
    primaryColor: '#6b7280',
    secondaryColor: '#9ca3af',
    accentColor: '#4ade80',
    bgGradientFrom: '#0f1117',
    bgGradientTo: '#1a1d27',
    cardBg: 'rgba(107, 114, 128, 0.08)',
    textPrimary: '#f9fafb',
    textSecondary: '#d1d5db',
    glowColor: 'rgba(74, 222, 128, 0.3)',
    particleColor: '#4ade80',
    fontFamily: '"Inter", sans-serif',
    particleType: 'bamboo',
    description: 'Calm and wise, your panda dwells in serene bamboo stillness.',
    personalities: ['lazy', 'intelligent', 'introverted', 'curious'],
  },
  fox: {
    species: 'fox',
    name: 'Autumn Fox',
    emoji: '🦊',
    primaryColor: '#f97316',
    secondaryColor: '#dc2626',
    accentColor: '#b45309',
    bgGradientFrom: '#1a0e00',
    bgGradientTo: '#2d1500',
    cardBg: 'rgba(249, 115, 22, 0.08)',
    textPrimary: '#fff7ed',
    textSecondary: '#fed7aa',
    glowColor: 'rgba(249, 115, 22, 0.4)',
    particleColor: '#f97316',
    fontFamily: '"Outfit", sans-serif',
    particleType: 'leaves',
    description: 'Cunning and wild, your fox dances through the autumn forest.',
    personalities: ['mischievous', 'curious', 'energetic', 'intelligent'],
  },
  dragon: {
    species: 'dragon',
    name: 'Cyber Dragon',
    emoji: '🐉',
    primaryColor: '#22d3ee',
    secondaryColor: '#a855f7',
    accentColor: '#eab308',
    bgGradientFrom: '#000814',
    bgGradientTo: '#001233',
    cardBg: 'rgba(34, 211, 238, 0.06)',
    textPrimary: '#e0f7fa',
    textSecondary: '#80deea',
    glowColor: 'rgba(34, 211, 238, 0.4)',
    particleColor: '#22d3ee',
    fontFamily: '"Space Grotesk", sans-serif',
    particleType: 'embers',
    description: 'Ancient and powerful, your dragon commands the digital realm.',
    personalities: ['intelligent', 'loyal', 'energetic', 'introverted'],
  },
  bunny: {
    species: 'bunny',
    name: 'Kawaii Bunny',
    emoji: '🐰',
    primaryColor: '#f472b6',
    secondaryColor: '#c084fc',
    accentColor: '#fb7185',
    bgGradientFrom: '#1a0a15',
    bgGradientTo: '#2d1230',
    cardBg: 'rgba(244, 114, 182, 0.08)',
    textPrimary: '#fdf2f8',
    textSecondary: '#fbcfe8',
    glowColor: 'rgba(244, 114, 182, 0.4)',
    particleColor: '#f472b6',
    fontFamily: '"Outfit", sans-serif',
    particleType: 'petals',
    description: 'Sweet and gentle, your bunny blooms in a pastel kawaii universe.',
    personalities: ['curious', 'energetic', 'loyal', 'mischievous'],
  },
};

export function getTheme(species: PetSpecies): PetTheme {
  return PET_THEMES[species];
}

export const DEFAULT_THEME = PET_THEMES.cat;

// CSS variable names mapped to theme properties
export function applyThemeToCSSVars(theme: PetTheme): Record<string, string> {
  return {
    '--color-primary': theme.primaryColor,
    '--color-secondary': theme.secondaryColor,
    '--color-accent': theme.accentColor,
    '--bg-gradient-from': theme.bgGradientFrom,
    '--bg-gradient-to': theme.bgGradientTo,
    '--card-bg': theme.cardBg,
    '--text-primary': theme.textPrimary,
    '--text-secondary': theme.textSecondary,
    '--glow-color': theme.glowColor,
    '--particle-color': theme.particleColor,
    '--font-family': theme.fontFamily,
  };
}
